# Generated by Django 2.0.5 on 2018-06-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nopely', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image_url',
            new_name='poster',
        ),
    ]
