# Generated by Django 2.0.5 on 2018-06-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nopely', '0003_auto_20180606_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
